#let thesis-type-title = "Bachelor's Thesis"
#let title-linebreak = [Linear Continuations in the\ Sequent Calculus Compiler]
#let title = [Linear Continuations in the Sequent Calculus Compiler]
#let author = "Rasmus Buurman"
#let university = "Eberhard Karls Universität Tübingen"
#let department = "Mathematisch-Naturwissenschaftliche Fakultät"
#let institute = "Wilhelm-Schickard-Institut für Informatik"
#let student-id = "6626679"
#let submission-date = [July 09, 2026]
#let period = [10.03.2026 -- 09.07.2026]
#let reviewer = "Dr. Philipp Schuster"
#let reviewer-university = "Eberhard Karls Universität Tübingen"
#let reviewer-department = "Wilhelm-Schickard-Institut für Informatik"
