#let thesis-type-title = "Bachelor's Thesis"
#let title-linebreak = [Linearity of Continuations in\ Sequent-Calculus-Based Compilation]
#let title = [Linearity of Continuations in Sequent-Calculus-Based Compilation]
#let author = "Rasmus Buurman"
#let university = "Eberhard Karls Universität Tübingen"
#let department = "Mathematisch-Naturwissenschaftliche Fakultät"
#let institute = "Wilhelm-Schickard-Institut für Informatik"
#let student-id = "6626679"
#let submission-date = [TBA]
#let period = [TBA]
#let reviewer = "Dr. Philipp Schuster"
#let reviewer-university = "Eberhard Karls Universität Tübingen"
#let reviewer-department = "Wilhelm-Schickard-Institut für Informatik"
